#!/usr/bin/env node
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const data = JSON.parse(fs.readFileSync('data/dashboard.json', 'utf8'));
const source = fs.readFileSync('app.js', 'utf8').replace(/bindEvents\(\); updateConnection\(\); loadData\(\);[\s\S]*$/, '');
const checks = `
state.data = data;
state.filters.activity = 'Jarras Blender | Cold Foam';
const module = state.data.quantityModules.find(item => item.activity === state.filters.activity);
assert(quantityChoices(module).some(item => item.value === 'blender|zero'));
const zero = new Set(state.data.submissions.filter(item => item.valid && item.activity === module.activity && item.quantities?.blender === 0).map(item => item.ceco));
state.filters.quantity = 'blender|zero';
assert.deepEqual(new Set(filteredStores().map(item => item.ceco)), zero);
assert(filteredQuantityResponses(module).every(item => item.quantities.blender === 0));
state.filters.quantity = 'blender|1-5';
assert(filteredQuantityResponses(module).every(item => item.quantities.blender >= 1 && item.quantities.blender <= 5));
state.filters.activity = 'FHW';
state.filters.quantity = 'cutlery|pending';
const fhwAnswered = new Set(state.data.submissions.filter(item => item.valid && item.activity === 'FHW' && item.quantities).map(item => item.ceco));
assert.equal(filteredStores().length, state.data.stores.length - fhwAnswered.size);
state.filters.quantity = 'cutlery|zero';
const fhwZero = state.data.submissions.filter(item => item.valid && item.activity === 'FHW' && item.quantities?.cutlery === 0).length;
assert.equal(filteredStores().length, fhwZero);
state.filters.activity = 'Organización Refrigeradores Back';
state.filters.quantity = '';
assert.equal(filteredStores().length, state.data.stores.length);
assert.equal(state.data.submissions.filter(item => item.activity === state.filters.activity && item.evidenceFiles?.length === 2).length >= 5, true);
state.filters.activity = 'Va X Cuenta';
const donation = activeQuantityModule();
assert.equal(donation.totalLabel, 'Plantilla reportada');
assert.deepEqual([donation.totals.yesDonate, donation.totals.noDonate, donation.totals.total, donation.totals.percentage], [13, 2, 15, 86.7]);
const regional = quantityRollup(filteredQuantityResponses(donation), donation.metrics, ['region'], donation.percentageMetric);
assert.deepEqual(regional.map(item => [item.labels[0], item.totals.total, item.totals.percentage]), [['Centro Norte',8,100],['Centro Sur',7,71.4]]);
state.filters.region = 'Centro Sur';
const portfolio = quantityRollup(filteredQuantityResponses(donation), donation.metrics, ['region','dm'], donation.percentageMetric);
assert.equal(portfolio.length, 1);
assert.deepEqual([portfolio[0].totals.yesDonate, portfolio[0].totals.noDonate, portfolio[0].totals.total, portfolio[0].totals.percentage], [5,2,7,71.4]);
state.filters.region = '';
state.filters.quantity = 'noDonate|zero';
assert.equal(filteredStores().map(item => item.ceco).join(','), '38925');
state.filters.quantity = '';
const spec = buildExcelSpec();
const donationSheet = spec.sheets.find(item => item.name === 'Va X Cuenta');
const summarySheet = spec.sheets.find(item => item.name === 'Participación');
assert.equal(donationSheet.rows[3].join(','), 'CeCo,Tienda,Región,DM,Sí dona,No dona,Plantilla reportada,% Sí dona,Evidencia');
assert.equal(donationSheet.rows.length, 6);
assert.equal(donationSheet.rows[4][7].value, 1);
assert.equal(summarySheet.rows[3].join(','), 'Ámbito,Región,Portafolio DM,Tiendas,Sí dona,No dona,Plantilla reportada,% Sí dona');
assert.equal(summarySheet.rows.length, 8);
`;
vm.runInNewContext(source + checks, {data, assert, console}, {filename:'app.js'});
console.log('Filtro numérico validado · cero · rangos · pendiente · cambio de actividad');
